chore(ci): add debug info to test artifact download
Description
---

Generated schema is uploaded to github artifact store. Then downloaded in next step, but cannot be found.
I added a debug step to see the contents.

```
Run mkdir -p gh-pages/schemas
  mkdir -p gh-pages/schemas
  set -e
  SCHEMA_FILE=$(ls schemas/*.json | head -n1)
  SCHEMA_BASENAME=$(basename "$SCHEMA_FILE")
  GH_PAGES_SCHEMA="gh-pages/schemas/$SCHEMA_BASENAME"
  if [ -f "$GH_PAGES_SCHEMA" ]; then
    if diff -q "$SCHEMA_FILE" "$GH_PAGES_SCHEMA" > /dev/null; then
      echo "Schema unchanged. Skipping publish."
      echo "skip_publish=true" >> $GITHUB_OUTPUT
    else
      cp -f "$SCHEMA_FILE" "$GH_PAGES_SCHEMA"
      echo "skip_publish=false" >> $GITHUB_OUTPUT
    fi
  else
    cp -f "$SCHEMA_FILE" "$GH_PAGES_SCHEMA"
    echo "skip_publish=false" >> $GITHUB_OUTPUT
  fi
  shell: /usr/bin/bash -e {0}
ls: cannot access 'schemas/*.json': No such file or directory
cp: cannot stat '': No such file or directory
Error: Process completed with exit code 1.
```

Motivation and Context
---

How Has This Been Tested?
---

What process can a PR reviewer use to test or verify this change?
---

<!-- Checklist -->
<!-- 1. Is the title of your PR in the form that would make nice release notes? The title, excluding the conventional commit
tag, will be included exactly as is in the CHANGELOG, so please think about it carefully. -->


Breaking Changes
---

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

<!-- Does this include a breaking change? If so, include this line as a footer -->
<!-- BREAKING CHANGE: Description what the user should do, e.g. delete a database, resync the chain -->